# Generated by Django 5.0.6 on 2024-05-18 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_comment_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='imdb_ratings_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_ratings_count',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_votes',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_votes_average',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='imdb_votes_count',
        ),
    ]
